In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import plotly.express as px
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import RobustScaler
from scipy.stats.mstats import winsorize
from sklearn.decomposition import PCA

In [3]:
raw_data = pd.read_csv('Customer_Data.csv')
raw_data

Customer_ID Customer_Status Old_Class  Geographical_ID  \
0           100001          Active         C                1   
1           100002          Active         C                1   
2           100003          Active         C                1   
3           100004          Active         C                1   
4           100005        Inactive         C                2   
...            ...             ...       ...              ...   
88805       188806          Active         C                5   
88806       188807          Active         C               18   
88807       188808          Active         C               18   
88808       188809          Active         C               18   
88809       188810          Active         C               19   

      CustCreationDate  Net_ Purchase(IRR)  Avg_Invoice_Row_No  Waste_Rate  \
0           2019-03-07                 0.0                 0.0         0.0   
1           2019-03-09                 0.0                 0.0         0.0   
2           2019-05-07                 0.0                 0.0         0.0   
3           2019-05-15                 0.0                 0.0         0.0   
4           2019-05-21                 0.0                 0.0         0.0   
...                ...                 ...                 ...         ...   
88805       2021-11-27                 0.0                 0.0         0.0   
88806       2021-11-27                 0.0                 0.0         0.0   
88807       2021-11-27                 0.0                 0.0         0.0   
88808       2021-11-27                 0.0                 0.0         0.0   
88809       2021-11-27                 0.0                 0.0         0.0   

       Rejected_Rate  Avg_Purchase_In_Month Date_Of_Last_ Purchase  \
0                0.0                      0             2020-01-11   
1                0.0                      0             2020-02-11   
2                0.0                      0             2020-02-29   
3                0.0                      0             2020-03-01   
4                0.0                      0             2020-02-09   
...              ...                    ...                    ...   
88805            0.0                      0             2022-02-03   
88806            0.0                      0             2022-02-03   
88807            0.0                      0             2022-02-03   
88808            0.0                      0             2022-02-03   
88809            0.0                      0             2022-02-03   

       Unnamed: 11  Unnamed: 12  
0              NaN          NaN  
1              NaN          NaN  
2              NaN          NaN  
3              NaN          NaN  
4              NaN          NaN  
...            ...          ...  
88805          NaN          NaN  
88806          NaN          NaN  
88807          NaN          NaN  
88808          NaN          NaN  
88809          NaN          NaN  

[88810 rows x 13 columns]

In [4]:
X = raw_data.drop(['Customer_ID','CustCreationDate','Date_Of_Last_ Purchase','Unnamed: 11','Unnamed: 12'],axis=1)
X

Customer_Status Old_Class  Geographical_ID  Net_ Purchase(IRR)  \
0              Active         C                1                 0.0   
1              Active         C                1                 0.0   
2              Active         C                1                 0.0   
3              Active         C                1                 0.0   
4            Inactive         C                2                 0.0   
...               ...       ...              ...                 ...   
88805          Active         C                5                 0.0   
88806          Active         C               18                 0.0   
88807          Active         C               18                 0.0   
88808          Active         C               18                 0.0   
88809          Active         C               19                 0.0   

       Avg_Invoice_Row_No  Waste_Rate  Rejected_Rate  Avg_Purchase_In_Month  
0                     0.0         0.0            0.0                      0  
1                     0.0         0.0            0.0                      0  
2                     0.0         0.0            0.0                      0  
3                     0.0         0.0            0.0                      0  
4                     0.0         0.0            0.0                      0  
...                   ...         ...            ...                    ...  
88805                 0.0         0.0            0.0                      0  
88806                 0.0         0.0            0.0                      0  
88807                 0.0         0.0            0.0                      0  
88808                 0.0         0.0            0.0                      0  
88809                 0.0         0.0            0.0                      0  

[88810 rows x 8 columns]

In [5]:
X_encoded = LabelEncoder().fit_transform(X.Customer_Status)
X.Customer_Status = X_encoded
X_encoded = LabelEncoder().fit_transform(X.Old_Class)
X.Old_Class = X_encoded
X

Customer_Status  Old_Class  Geographical_ID  Net_ Purchase(IRR)  \
0                    0          3                1                 0.0   
1                    0          3                1                 0.0   
2                    0          3                1                 0.0   
3                    0          3                1                 0.0   
4                    1          3                2                 0.0   
...                ...        ...              ...                 ...   
88805                0          3                5                 0.0   
88806                0          3               18                 0.0   
88807                0          3               18                 0.0   
88808                0          3               18                 0.0   
88809                0          3               19                 0.0   

       Avg_Invoice_Row_No  Waste_Rate  Rejected_Rate  Avg_Purchase_In_Month  
0                     0.0         0.0            0.0                      0  
1                     0.0         0.0            0.0                      0  
2                     0.0         0.0            0.0                      0  
3                     0.0         0.0            0.0                      0  
4                     0.0         0.0            0.0                      0  
...                   ...         ...            ...                    ...  
88805                 0.0         0.0            0.0                      0  
88806                 0.0         0.0            0.0                      0  
88807                 0.0         0.0            0.0                      0  
88808                 0.0         0.0            0.0                      0  
88809                 0.0         0.0            0.0                      0  

[88810 rows x 8 columns]

In [6]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
X_pca

array([[-4.60426172e+08, -1.09361714e+00],
       [-4.60426172e+08, -1.09361714e+00],
       [-4.60426172e+08, -1.09361714e+00],
       ...,
       [-4.60426172e+08, -1.09799375e+00],
       [-4.60426172e+08, -1.09799375e+00],
       [-4.60426172e+08, -1.09825120e+00]], shape=(88810, 2))

In [7]:
komponen = pca.components_
komponen

array([[-6.91796829e-11, -2.38600584e-10,  1.71227505e-10,
         1.00000000e+00,  2.97666752e-09, -5.21460002e-11,
        -3.08808781e-10,  1.02673062e-08],
       [-9.32765402e-07, -1.34471766e-04, -2.57447502e-04,
         3.23828913e-10, -3.70212071e-04,  1.92437535e-02,
         9.99813914e-01, -1.26227667e-03]])

In [8]:
pca.explained_variance_ratio_

array([1.00000000e+00, 1.16766976e-14])